# Generated by Django 6.0.3 on 2026-03-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('bg_removed_image', models.ImageField(blank=True, null=True, upload_to='processed/bg_removed/')),
                ('enhanced_image', models.ImageField(blank=True, null=True, upload_to='processed/enhanced/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
