# Generated by Django 5.2.12 on 2026-04-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0004_subscriptionplan_alter_imagetask_bg_removed_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
